services:
  mongodb:
    image: mongo:7
    restart: always
    container_name: database
    environment:
      MONGO_INITDB_DATABASE: library_example
    ports:
      - "27017:27017"
    
  dbgate:
    image: dbgate/dbgate
    container_name: dbgate
    restart: always
    ports:
      - 3000:3000
    environment:
      INSTALL_PLUGINS: dbgate-plugin-mongo

      CONNECTIONS: con1

      #mongodb conn
      LABEL_con1: "MongoDB"
      SERVER_con1: mongodb
      PORT_con1: 27017
      ENGINE_con1: mongo@dbgate-plugin-mongo

    depends_on:
      - mongodb